Umbrella feeds contract re-write from sol to rust with ed25519 signature & tests
buidly/sc-umbrella-network-rs pull request #1
Opened 2023-07-10 08:19 UTC by raress96

2023-07-13 09:53 UTC, alexjilavu requested changes

2023-07-13 09:53 UTC, alexjilavu commented on umbrella-feeds/src/lib.rs
> +        // require!(price_keys.len() == price_datas.len(), "Arrays data do not match");
Is this supposed to be commented?

2023-07-13 09:53 UTC, alexjilavu commented on umbrella-feeds/src/lib.rs
> +            data.push(self.prices(&key).get());
what happens if self.prices(&key) is empty?

2023-07-13 09:53 UTC, alexjilavu commented on umbrella-feeds/src/lib.rs
> +    fn verify_signatures(
I also see a view for this function in the EVM SC

2023-07-13 09:53 UTC, alexjilavu commented on umbrella-feeds/src/proxy.rs
> +pub mod staking_bank_proxy {
Since you are importing staking-bank-static-local in Cargo.toml; you could directly use the proxy from there. Either do that, or remove the import from Cargo.toml since I don't think you use it elsewhere

2023-07-17 10:10 UTC, raress96 commented on umbrella-feeds/src/lib.rs
> +        // require!(price_keys.len() == price_datas.len(), "Arrays data do not match");
That's how it is in sol contract also, to save on gas.

2023-07-17 10:46 UTC, raress96 commented on umbrella-feeds/src/lib.rs
> +            data.push(self.prices(&key).get());
There will be an error. This is a view, so it will be called externally and the caller has to make sure what it sends are valid keys. I don't see that we need to do anything else here.

2023-07-17 10:46 UTC, raress96 commented on umbrella-feeds/src/lib.rs
> +    fn verify_signatures(
Added.

2023-07-31 12:14 UTC, DZariusz reviewed
I think we missing some views:
- hashData
- getChainId
- recoverSigner

can we add them? they are super usefull for debugging.

2023-07-31 12:14 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +            data.push(self.prices(&key).get());
- `getManyPriceData` should revert if data is empty 
- `getManyPriceDataRaw` does not revert - it will return empty data

2023-07-31 12:14 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +    fn get_price_data(&self, key: ManagedBuffer) -> PriceData<Self::Api> {
we missing `if (data.timestamp == 0) revert FeedNotExist();`

2023-07-31 12:14 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +        self.prices(&key).get().price
we missing `if (data.timestamp == 0) revert FeedNotExist();`

2023-07-31 12:14 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +        let price = self.prices(&key).get();
we missing `if (data.timestamp == 0) revert FeedNotExist();`

2023-07-31 12:14 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +        let price: PriceData<Self::Api> = self.prices(&key).get();
we missing `if (data.timestamp == 0) revert FeedNotExist();`

2023-07-31 13:56 UTC, raress96 commented on generate-signature/alice.pem
> +-----BEGIN PRIVATE KEY for erd1qyu5wthldzr8wx5c9ucg8kjagg0jfs53s8nr3zpz3hypefsdd8ssycr6th-----
This particular `.pem` file is actually a common wallet available from MultiversX sdk directly.

However, a pem file can be generated using `mxpy` cli:

`mxpy wallet new --format pem --outfile wallet.pem`

Or from other wallet utilities.

2023-07-31 14:04 UTC, raress96 commented
> I think we missing some views:
> 
> * hashData
> * getChainId
> * recoverSigner
> 
> can we add them? they are super usefull for debugging.

The following functions can not be implemented on MultiversX:
- getChainId - there is no way to get the current chain id from the contract, hence it is not included in the hash data
- recoverSigner - since we use a different hash function, this is not needed and also not possible to implement on MultiversX currently

Added a view for `hashData` and also tested the other prices views to make sure they behave the same between the Sol and Rust implementations.

2023-08-01 12:09 UTC, DZariusz requested changes

2023-08-01 12:09 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +            "Signatures out of order"
I think this is a bug. here we checking only if signature is correct or not, it has nothing to do with orders. Orders should be check inside `verify_signatures()` and this check is missing.

2023-08-01 12:09 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +        require!(self.verify_validators(validators), "Invalid signer");
I do not understand this line, we calling `self.verify_validators` but I see no implementation of that fn inside this lib. How does it work?

2023-08-01 12:36 UTC, raress96 commented on umbrella-feeds/src/lib.rs
> +        require!(self.verify_validators(validators), "Invalid signer");
The `verify_validators` is implemented inside the `proxy.rs` file which contains the `ProxyModule` trait.

And since the `UmbrellaFeeds` trait from `lib.rs` implements the `ProxyModule` trait, those methods are also accessible here.

2023-08-01 12:45 UTC, raress96 commented on umbrella-feeds/src/lib.rs
> +            "Signatures out of order"
This is the error equivalent to this line:
https://github.com/umbrella-network/phoenix/blob/develop/contracts/onChainFeeds/UmbrellaFeeds.sol#L207

I just kept the error message the same, even though in this case it doesn't really make sense since like you said there is no actual "order" checked.

The crypto algorithm is completely different so checking the order is irrelevant. From what I understood from the .sol code, there it is done that way since the empty address `0x0` (which can be returned by `recoverSigner` if the signature is invalid) is actually "less" then a valid address, so it basically checks if the address returned from `recoverSigner` is a valid address and not `0x0`. Please correct me if I am wrong here.

We can change the messages to `Invalid signature` or something else to be more clear on what is actually being checked here.

2023-08-02 10:15 UTC, DZariusz commented on umbrella-feeds/src/lib.rs
> +            "Signatures out of order"
Order has nothing to do with crypto algorithm. Order prevents reusing same signatures multiple times. Please implement order check that we have inside `verifySignatures()` method. Please also add unit test that covers that bug. You can see this test in our repo under name `test_UmbrellaFeeds_update_failWhenSignaturesNotInOrder`.

2023-09-11 07:28 UTC, alexjilavu approved these changes

2023-09-11 13:45 UTC, merged